name: "document_approval"
description: "Document approval workflow with review stages"
stages:
  draft:
    name: "Draft"
    description: "Document is in draft status"
    expected_properties:
      document_id: {type: "str"}
      title: {type: "str"}
      content: {type: "str"}
      author: {type: "str"}
    gates:
      - name: "submit_for_review"
        description: "Submit document for review"
        target_stage: "under_review"
        locks:
          - type: exists
            property_path: "document_id"
          - type: exists
            property_path: "title"
          - type: exists
            property_path: "content"
          - type: exists
            property_path: "author"
          - type: not_empty
            property_path: "content"

  under_review:
    name: "Under Review"
    description: "Document is being reviewed"
    expected_properties:
      assigned_reviewer: {type: "str"}
      review_started_at: {type: "str"}
      review:
        decision: {type: "str"}
        completed_at: {type: "str"}
        feedback: {type: "str"}
    gates:
      - name: "approve_document"
        description: "Document approved by reviewer"
        target_stage: "approved"
        locks:
          - type: exists
            property_path: "review.decision"
          - type: equals
            property_path: "review.decision"
            expected_value: "approved"
          - type: exists
            property_path: "review.completed_at"
      - name: "request_changes"
        description: "Changes requested by reviewer"
        target_stage: "needs_revision"
        locks:
          - type: exists
            property_path: "review.decision"
          - type: equals
            property_path: "review.decision"
            expected_value: "changes_requested"
          - type: exists
            property_path: "review.feedback"

  needs_revision:
    name: "Needs Revision"
    description: "Document needs changes before approval"
    expected_properties:
      review:
        feedback: {type: "str"}
        requested_changes: {type: "list"}
      revision:
        completed: {type: "bool"}
        changes_made: {type: "str"}
    gates:
      - name: "resubmit_after_revision"
        description: "Resubmit document after making changes"
        target_stage: "under_review"
        locks:
          - type: exists
            property_path: "revision.completed"
          - type: equals
            property_path: "revision.completed"
            expected_value: true
          - type: exists
            property_path: "revision.changes_made"

  approved:
    name: "Approved"
    description: "Document has been approved"
    expected_properties:
      approved_by: {type: "str"}
      approved_at: {type: "str"}
      publish_ready: {type: "bool"}
    gates:
      - name: "publish_document"
        description: "Publish approved document"
        target_stage: "published"
        locks:
          - type: exists
            property_path: "approved_by"
          - type: exists
            property_path: "approved_at"
          - type: exists
            property_path: "publish_ready"
          - type: equals
            property_path: "publish_ready"
            expected_value: true

  published:
    name: "Published"
    description: "Document has been published"
    expected_properties:
      published_at: {type: "str"}
      publication_url: {type: "str"}
    gates: []
    is_final: true

initial_stage: "draft"
final_stage: "published"