name: "user_onboarding"
description: "User onboarding workflow with multiple stages"
stages:
  email_signup:
    name: "Email Signup"
    description: "User provides email and creates account"
    expected_properties:
      email: {type: "str"}
      user_id: {type: "str"}
      email_verified_at: {type: "str"}
    gates:
      - name: "email_verified"
        description: "Email verification completed"
        target_stage: "profile_setup"
        locks:
          - exists: "email"
          - exists: "user_id"
          - exists: "email_verified_at"
          - regex:
              property_path: "email"
              expected_value: "^[^@]+@[^@]+\\.[^@]+$"

  profile_setup:
    name: "Profile Setup"
    description: "User completes profile information"
    expected_properties:
      profile:
        first_name: {type: "str"}
        last_name: {type: "str"}
    gates:
      - name: "profile_complete"
        description: "Profile information is complete"
        target_stage: "verification"
        locks:
          - exists: "profile.first_name"
          - exists: "profile.last_name"
          - greater_than:
              property_path: "profile.first_name"
              expected_value: ""

  verification:
    name: "Verification"
    description: "Identity verification process"
    expected_properties:
      verification:
        document_uploaded: {type: "bool"}
        status: {type: "str"}
    gates:
      - name: "verification_approved"
        description: "Identity verification approved"
        target_stage: "active_user"
        locks:
          - equals:
              property_path: "verification.document_uploaded"
              expected_value: true
          - equals:
              property_path: "verification.status"
              expected_value: "approved"

  active_user:
    name: "Active User"
    description: "User account is fully active"
    expected_properties:
      status: {type: "str"}
      activated_at: {type: "str"}
    gates: []
    is_final: true

initial_stage: "email_signup"
final_stage: "active_user"